### ISSUE TITLE
How to search array by text or by id and reflect results to the screen

### ISSUE THREAD

**Issue by yznetaX** [mhdabdelrhman/AutomatedAnswer#12]
Dear Mohamad
Thank you for your time, i have a question which cross my mind, as we know, we have an id for each node in the tree, lets say I want to view the id path.
The idea that i will show the full tree as nested tree in other page, it will be good idea if user click on any node to take user to the scenario Builder, and render the options so he can see the option he click on, this way it will be easy to find any node.
Or we can add a search box so user can search the array by text, and the results will be reflected on the screen

**Comment by mhdabdelrhman** [comment]
we can apply search on the `Chain`  object and select the result `Path`, then the UI will automatically change according to the selection:
- write search scenario (as text).
- prepare UI for search (as image).

#### Implementation will be
- user write text in search input.
- user press search.
- search service will take the `Chain` object and `Search key words` as parameters.
- search service will start from top and start search on text and id.
- search service will remember the path.
- if result founded the path will select.
- service can give many results.

**Comment by yznetaX** [comment]
Dear Mohamd.

So you mean we have to do recarcive search by keyword, i can store the id and the text results in an array. And i will display a menu of the results... But we only have id of the node. 

I dont understand the path section, can you explain

And where should i pass the results to reflect to the screen 
@mhdabdelrhman
