### ISSUE TITLE
Ordering options - box sizing - empty bix validation - css enhancement

### ISSUE THREAD

**Issue by beshoo** [mhdabdelrhman/AutomatedAnswer#14]
Dear all, while testing i note the following 
![20200614_031321](https://user-images.githubusercontent.com/4635115/84581752-51d52900-aded-11ea-816d-18c2aeec69aa.jpg)

Moreover 
- There is no validation if user leaves the option empty. User can not creat children of any option if he left it empty.. @yznetaX  i believe we have to disable next welcome box if he left the option empty, and if he saved we filter out the empty options

- There's no validation if user leaves the `first` welcome box empty..  (only the first one is mandatory ) 
The welcome box can accept new line and it will resize the hight accordingly.` As chatra.io` 

For team attention. 
https://github.com/mhdabdelrhman/AutomatedAnswer/issues/9

**Comment by mhdabdelrhman** [comment]
`hotfix/focus` branch merged with `master`

**Comment by mhdabdelrhman** [comment]
I think this issue was done

@beshoo  @yznetaX

**Comment by mhdabdelrhman** [comment]
please if it is OK , you can close this issue
![image](https://user-images.githubusercontent.com/16289510/85898553-1da63300-b805-11ea-8284-3235d618d24c.png)
