### ISSUE TITLE
Bug with save function

### ISSUE THREAD

**Issue by beshoo** [mhdabdelrhman/AutomatedAnswer#16]
Hi.
If the user updates the option, the save buttons appear. and the user can cancel the changes.
The BUG
If the user refreshes the window without saving, the reset and save button disappear and the changes remain.

I believe, we only save the tree if the user clicks save!

**Update:**
It is nice to save the tree in the localStoreg , but if the user reload the window - he has to be able to see the save and the cancel buttons.

**Comment by yznetaX** [comment]
and actually we want to make chain and backup for chain in localStorage then when user click cancel the backup chain will appear and
 like chatra every scenario must have his own chain tree
@mhdabdelrhman
