### ISSUE TITLE
Fix bug: Select reply option

### ISSUE THREAD

**Issue by mhdabdelrhman** [mhdabdelrhman/AutomatedAnswer#2]
![image](https://user-images.githubusercontent.com/16289510/84114281-c3e7ef80-aa34-11ea-9203-48e7794bac58.png)

**Comment by yznetaX** [comment]
there is a bug in the reply fields 
and this gif will explained this bug
http://mujeebk.com/panel/testone.gif

**Comment by beshoo** [comment]
I confirm this bug +1
- Please make the input box of the option turn blue on hover as it is good feedback to the user!

**Comment by mhdabdelrhman** [comment]
- I created branch [Fixbug/select-option](https://github.com/mhdabdelrhman/AutomatedAnswer/tree/Fixbug/select-option)

- I fixed the bug, and created pull request, please move to pull request (#7) and review the code, notify me if every think is `Ok`, to merge [Fixbug/select-option](https://github.com/mhdabdelrhman/AutomatedAnswer/tree/Fixbug/select-option)

@beshoo @yznetaX
