### ISSUE TITLE
Implement Dialog options

### ISSUE THREAD

**Issue by mhdabdelrhman** [mhdabdelrhman/AutomatedAnswer#3]
Regarding the dialog...It is very simple.Once the user chose to add dialog he will have a model popup with the following optionDialog Text [    ]Dialog type [Dropdown] => Send Text, [ (Send Photo, Send-Document, Send Voice, Send Video ) when we chose one of these options we will have to choose between add URL of the file or upload it to the server which will be like this]File URL [               ] | OR Upload file [                ] => if he chose to upload then we will post to the server and show small progress par.That's it.and once he saves we will add the dialog to the scenario with different color and we will show a small pen icon to let the user update the information.Sure we can delete any and we will alert the user if there is a nested tree that we will delete everything related to the tree.
Please be aware of the dialog if we delete the parent tree and this parent has some dialogs which have upload properties, we need to fetch all uploaded IDs to post them back to the server in order to delete the file from the server.and if we delete one dialog and it has uploaded file we will post to the server to delete them from the server.
I believe the best way to save time to make a method that you call it and pass the ids of the upload dialogs then post to the server upon delete. the delete will happen once user hit saves so if there are upload dialogs to delete we will send the new the object as following :
``` javascript
tree:{{
        "id": "oRmWTyrKpLRwKMy2o",
        "text": {
            "en": "Welcome string"
        },
        "replies": [
            {
                "id": "gf6euCBwT8iQg2TTi",
                "text": {}      }

},deleted_dialogs{          id:[                  array of ids or URL what ever              ]}
```

- send axios apis  to check the dialog data before saving it.

**Comment by beshoo** [comment]
Let me please reformat the context:
Once the user chose to add dialog he will have a **model popup** with the following option
`Dialog Text : [               ]`
`Dialog type [Dropdown Menu]` =>
```
1. Send Text [Text] [Required] 
2. Send Photo [URL | Upload] [Required] 
3. Send-Document [URL | Upload] [Required] 
4. Send Voice [URL | Upload] [Required] 
5. Send Video [URL | Upload] [Required] 
6. Send Data From RSS Feed [URL] [Required] 
```
When the user chose to send a "file" he will have another input box under the previous select menu
Which is as following 
`Document URL : [              ]` OR `Upload File [                       ]`

If the user chose to close the dialog, we will call a method to check the user input (we already talked about it), to return the validation object with true or false. we will do the ajax call in that method.

**Comment by beshoo** [comment]
Users may choose to delete the dialog, but as long as we don't reflect that to the server right away, we need to save the deleted dialog in an array. Which it may contain the id of the deleted dialogs.
I will use the dialog id as the `NAME` of the uploaded document.

So when user **UPLOAD** the document we will send the `dialog_id` along with the POST request in order to be able to grep the `dialog_id` and use it as filename, then it will be more convenient to save the **dialog_id** in the deleted dialog.

If user chose to upload a document - we will have a small loader `|||||||||| 60%` as upload feedback.
I believe it will be underneath the  upload filed 
`URL[ _______ ] `or `Upload [ __________ ]` [upload will start once user chose the file]
____Upload Progress Bar` [ ||||||||||| 60% ] `<= will appear once user the file

**Comment by beshoo** [comment]
In the main scenario screen, if the user adds a dialog, and he wants to edit the dialog context, he will click on the dialog then he will have the popup, it is more convenient than add a pin icon as edit action.

This means the user can not edit the `**dialog TEXT**` form the main screen, only options can be edit from the main screen.

**Comment by mhdabdelrhman** [comment]
The dialog almost finished, I added a function at [utils.js](https://github.com/mhdabdelrhman/AutomatedAnswer/blob/b9719deb9cca34eaf39e291ee66d7c89eeac1bfb/src/components/automated/utils.js#L38) file for posting the data before saving to the server. 

``` js
export const postDataToServer = function(dialogData) {
  // post to the server
  // response must be an object like
  /* 
      {
        success:true,// true or false
        error:"",// error message if exists
        url:"", // url to the file or the url set by user
      }
  */


  ...


  return axios
    .post(checkApiUrl, formData)
    .then((response) => {
      return response.data;
    })
    .catch((er) => {
      return { success: false, error: er, url: null };
    });
};

```

you need to assign `checkApiUrl` value at the [beginning of the file](https://github.com/mhdabdelrhman/AutomatedAnswer/blob/b9719deb9cca34eaf39e291ee66d7c89eeac1bfb/src/components/automated/utils.js#L3).
``` js
const baseUrl = "https://server-url.com/api/";
const checkApiUrl = baseUrl + "check/";
```

**Comment by beshoo** [comment]
Please do not forget if user delete an option to collect all dialogs ids under that option and save it in deleteed_dialog to send it to the server once user save

@mhdabdelrhman
