### ISSUE TITLE
Save the tree to the local store

### ISSUE THREAD

**Issue by mhdabdelrhman** [mhdabdelrhman/AutomatedAnswer#4]
we need to save the tree to the local storage so you render it from local storage:
- create branch `feature/storage` from `master`
- the work will be at this [file](https://github.com/mhdabdelrhman/AutomatedAnswer/blob/master/src/components/automated/Conversation.vue)
- create method to load from storage and return `Chain` object.
- create method to save `Chain` object to local storage.
- use the methods when pressing save and when load the component.
- use (#4) reference at the beginning of the commits.
![image](https://user-images.githubusercontent.com/16289510/84494619-82fd0e80-acb2-11ea-96ac-6d2948fb81d5.png)
for example 
```
(#4) save chain to local storage
```
- create pull request.
- don't merge please.

**Comment by yznetaX** [comment]
see here https://app.chatra.io/ 
i want to be like this
when i reload the page my progress saved to localStorage with out click on save

**Comment by yznetaX** [comment]
i think this function will be on every field 
any idea ??

**Comment by mhdabdelrhman** [comment]
> i think this function will be on every field
> any idea ??

I think we don't need to add it to every filed
- now implement the methods
- I will see the link 

> see here https://app.chatra.io/
> i want to be like this
> when i reload the page my progress saved to localStorage with out click on save

**Comment by mhdabdelrhman** [comment]
at the beginning we can use `timer` to save every 2 seconds, then we can use `events` or vue `watch`

**Comment by yznetaX** [comment]
ok that will be good
