### ISSUE TITLE
[Request] Add new option if user press enter key 

### ISSUE THREAD

**Issue by beshoo** [mhdabdelrhman/AutomatedAnswer#6]
You can create an options by clicking on the add option button.

It will be more convenient if we can add a new option once user press the enter key  after finish typing the current option. 
The new option will be ready to type in by moving fucus to the new option. 

This is only with option function. 
As chatra.io 
Regard.

**Comment by beshoo** [comment]
I believe Yazan did that, but he struggling how to create a pull request from the command line
@yznetaX , Did you make it. I am sorry I did not follow with you today cos I have a critical situation in my family, my aunt has passed away :(

**Comment by mhdabdelrhman** [comment]
I will write the steps [here](https://github.com/mhdabdelrhman/AutomatedAnswer/wiki/How-to-be-partner-in-this-project%3F)
