### ISSUE TITLE
Empty First welcome box and options fileds is not allowed even after save  

### ISSUE THREAD

**Issue by beshoo** [mhdabdelrhman/AutomatedAnswer#9]
As we already have now 
The first time user want to creat the senario, the welcome box is mandatory. 

Now the expected senario after save is
User try to empty the first welcome box. (not allowed ) `but the rest of welcome boxs user can to leav it empty `

User may try to empty an option /dialog (delete the words) this is not allowed 

User may try to add an empty option, this is not allowed.  The next section will only appear if he type. 

An alarm has to take a place that the filed is mandatory. 

Regard

**Comment by mhdabdelrhman** [comment]
this is done already
@beshoo  @yznetaX

**Comment by mhdabdelrhman** [comment]
please if it is OK , you can close this issue
![image](https://user-images.githubusercontent.com/16289510/85898516-06674580-b805-11ea-9eca-7b1cb8351be0.png)
